// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbN0OThe2GvT0c8ZUrICdHDoA3sgh1hu0',
    appId: '1:385080465045:web:03e5965caebb222eb16d9c',
    messagingSenderId: '385080465045',
    projectId: 'ecommarce-by-jakir',
    authDomain: 'ecommarce-by-jakir.firebaseapp.com',
    storageBucket: 'ecommarce-by-jakir.firebasestorage.app',
    measurementId: 'G-M5X3BXERNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVkQpZ4MnLruurIA8A4vlxuVjzzzIJxiM',
    appId: '1:385080465045:android:5ece4cb7ec578825b16d9c',
    messagingSenderId: '385080465045',
    projectId: 'ecommarce-by-jakir',
    storageBucket: 'ecommarce-by-jakir.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP0AAuofGImD7PUzfMMXPknOeFHnyeZKI',
    appId: '1:385080465045:ios:88bc0f410a8947c1b16d9c',
    messagingSenderId: '385080465045',
    projectId: 'ecommarce-by-jakir',
    storageBucket: 'ecommarce-by-jakir.firebasestorage.app',
    iosBundleId: 'com.example.j27',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP0AAuofGImD7PUzfMMXPknOeFHnyeZKI',
    appId: '1:385080465045:ios:88bc0f410a8947c1b16d9c',
    messagingSenderId: '385080465045',
    projectId: 'ecommarce-by-jakir',
    storageBucket: 'ecommarce-by-jakir.firebasestorage.app',
    iosBundleId: 'com.example.j27',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbN0OThe2GvT0c8ZUrICdHDoA3sgh1hu0',
    appId: '1:385080465045:web:118eeede7f23fb14b16d9c',
    messagingSenderId: '385080465045',
    projectId: 'ecommarce-by-jakir',
    authDomain: 'ecommarce-by-jakir.firebaseapp.com',
    storageBucket: 'ecommarce-by-jakir.firebasestorage.app',
    measurementId: 'G-0KYT1MLVG6',
  );
}
